'use client';

import Link from 'next/link';

export function AppFooter() {
    return (
        <footer className={'border-t border-indigo-200 dark:border-indigo-800 py-2'}>
            <div className="px-4">
                <div className="flex items-center justify-center">
                    <p className="text-xs text-gray-500 dark:text-gray-400">
                        Generated by{' '}
                        <Link
                            href="https://github.com/solana-developers/create-solana-dapp"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="hover:text-indigo-900 dark:hover:text-indigo-500"
                        >
                            create-solana-dapp
                        </Link>
                        .
                    </p>
                </div>
            </div>
        </footer>
    );
}
