'use client';

import { AccountUiChecker } from '@/components/account/ui/account-ui-checker';
import { Menu, X } from 'lucide-react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ReactNode, useState } from 'react';
import { ClusterChecker } from './cluster-checker';
import { ClusterSelect } from './cluster-select';
import { ThemeProvider } from './theme-provider';
import { ThemeSelect } from './theme-select';
import { Button } from './ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogTitle, DialogTrigger } from './ui/dialog';
import { Toaster } from './ui/sonner';
import { ConnectWalletMenu } from './wallet-ui';

export function AppLayout({ children, links }: { children: ReactNode; links: { label: string; path: string }[] }) {
    return (
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <div className="flex flex-col min-h-screen">
                <AppHeader links={links} />
                <main className="flex-grow container mx-auto p-4">
                    <ClusterChecker>
                        <AccountUiChecker />
                    </ClusterChecker>
                    {children}
                </main>
                <AppFooter />
            </div>
            <Toaster />
        </ThemeProvider>
    );
}

export function AppHeader({ links = [] }: { links: { label: string; path: string }[] }) {
    const pathname = usePathname();
    const [showMenu, setShowMenu] = useState(false);

    return (
        <header className="relative z-50 px-4 py-2 bg-gray-100 dark:bg-gray-900 dark:text-gray-400">
            <div className="mx-auto flex justify-between items-center">
                <div className="flex items-baseline gap-4">
                    <Link className="text-xl hover:text-gray-500 dark:hover:text-white" href="/">
                        <span>Placeholder</span>
                    </Link>
                    <div className="hidden md:flex items-center">
                        <ul className="flex gap-4 flex-nowrap items-center">
                            {links.map(({ label, path }) => (
                                <li key={path}>
                                    <Link
                                        className={`hover:text-gray-500 dark:hover:text-white ${pathname?.startsWith(path) ? 'text-gray-500 dark:text-white' : ''}`}
                                        href={path}
                                    >
                                        {label}
                                    </Link>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>

                <Button variant="ghost" size="icon" className="md:hidden" onClick={() => setShowMenu(!showMenu)}>
                    {showMenu ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
                </Button>

                <div className="hidden md:flex items-center gap-4">
                    <ConnectWalletMenu>Connect Wallet</ConnectWalletMenu>
                    <ClusterSelect />
                    <ThemeSelect />
                </div>

                {showMenu && (
                    <div className="md:hidden fixed inset-x-0 top-[52px] bottom-0 bg-gray-100/95 dark:bg-gray-900/95 backdrop-blur-sm">
                        <div className="flex flex-col p-4 gap-4 border-t dark:border-gray-800">
                            <ul className="flex flex-col gap-4">
                                {links.map(({ label, path }) => (
                                    <li key={path}>
                                        <Link
                                            className="hover:text-gray-500 dark:hover:text-white block text-lg py-2"
                                            href={path}
                                            onClick={() => setShowMenu(false)}
                                        >
                                            {label}
                                        </Link>
                                    </li>
                                ))}
                            </ul>
                            <div className="flex flex-col gap-4">
                                <ConnectWalletMenu>Connect Wallet</ConnectWalletMenu>
                                <ClusterSelect />
                                <ThemeSelect />
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </header>
    );
}

export function AppFooter() {
    return (
        <footer className="text-center p-2 bg-gray-100 dark:bg-gray-900 dark:text-gray-400">
            Generated by{' '}
            <a
                className="link hover:text-gray-500 dark:hover:text-white"
                href="https://github.com/solana-developers/create-solana-dapp"
                target="_blank"
                rel="noopener noreferrer"
            >
                create-solana-dapp
            </a>
        </footer>
    );
}

export function AppHero({
    children,
    title,
    subtitle,
}: {
    children?: ReactNode;
    title?: ReactNode;
    subtitle?: ReactNode;
}) {
    return (
        <div className="flex flex-row justify-center py-[64px]">
            <div className="text-center">
                <div className="max-w-2xl">
                    {typeof title === 'string' ? <h1 className="text-5xl font-bold">{title}</h1> : title}
                    {typeof subtitle === 'string' ? <p className="py-6">{subtitle}</p> : subtitle}
                    {children}
                </div>
            </div>
        </div>
    );
}

export function AppModal({
    children,
    title,
    disabled,
    description,
    onOpenChange,
    open,
    submit,
    submitDisabled,
    submitLabel,
}: {
    children: ReactNode;
    title: string;
    description: string;
    disabled?: boolean;
    onOpenChange: (open: boolean) => void;
    open: boolean;
    submit?: () => void;
    submitDisabled?: boolean;
    submitLabel?: string;
}) {
    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogTrigger asChild>
                <Button disabled={disabled}>{title}</Button>
            </DialogTrigger>
            <DialogContent>
                <DialogTitle>{title}</DialogTitle>
                <DialogDescription>{description}</DialogDescription>
                {children}
                <DialogFooter>
                    {submit ? (
                        <Button variant="default" onClick={submit} disabled={submitDisabled}>
                            {submitLabel || 'Save'}
                        </Button>
                    ) : null}
                    <Button variant="secondary" onClick={() => onOpenChange(false)}>
                        Close
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
