import { AppLayout } from '@/components/app-layout.tsx';
import { AppProviders } from '@/components/app-providers';
import type { Metadata } from 'next';
import './globals.css';
import React from 'react';

declare global {
    interface BigInt {
        toJSON(): string;
    }
}

BigInt.prototype.toJSON = function () {
    return this.toString();
};

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const links = [
    { label: 'Account', to: '/account' },
    { label: 'Cluster', to: '/cluster' },
    { label: 'Client', to: '/client' },
    { label: 'UI', to: '/ui' },
    { label: 'Wallets', to: '/wallets' },
];

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`antialiased`}>
                <AppProviders>
                    <AppLayout links={links}>{children}</AppLayout>
                </AppProviders>
            </body>
        </html>
    );
}
