name: Compare bundle size

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened]

permissions:
  contents: read

env:
  # Among other things, opts out of Turborepo telemetry
  # See https://consoledonottrack.com/
  DO_NOT_TRACK: '1'
  # Some tasks slow down considerably on GitHub Actions runners when concurrency is high
  TURBO_CONCURRENCY: 1
  # Enables Turborepo Remote Caching.
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  measure-bundlesize:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm turbo compile:js --concurrency=${TURBO_CONCURRENCY:-1}

      - name: BundleMon
        uses: lironer/bundlemon-action@4b47df0793e18e3899eeb07f19b7c88c92c2490e # v1.4.0
        env:
          # Always compare to the main branch; prevents stacked PRs from being
          # compared to the wrong mergebase (ie. the PR beneath the current one)
          CI_TARGET_BRANCH: main
