name: Publish pkg.pr.new

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm build

      - name: Publish to pkg.pr.new
        run: pnpm pkg-pr-new publish './packages/*'
